tabu = int(input('Digite um número: '))
print('A tabuada é...')
print('-' * 12)
print('{} x 1 = {:2}'.format(tabu, tabu * 1))
print('{} x 2 = {:2}'.format(tabu, tabu * 2))
print('{} x 3 = {:2}'.format(tabu, tabu * 3))
print('{} x 4 = {:2}'.format(tabu, tabu * 4))
print('{} x 5 = {:2}'.format(tabu, tabu * 5))
print('{} x 6 = {:2}'.format(tabu, tabu * 6))
print('{} x 7 = {:2}'.format(tabu, tabu * 7))
print('{} x 8 = {:2}'.format(tabu, tabu * 8))
print('{} x 9 = {:2}'.format(tabu, tabu * 9))
print('{} x 10 = {:2}'.format(tabu, tabu * 10))
print('-' * 12)
